# Generated by Django 4.2.15 on 2025-04-30 15:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manuscripts", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INVITED", "已邀请"),
                            ("ACCEPTED", "已接受"),
                            ("DECLINED", "已拒绝"),
                            ("IN_PROGRESS", "审稿中"),
                            ("COMPLETED", "已完成"),
                        ],
                        default="INVITED",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "invited_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="邀请日期"),
                ),
                (
                    "response_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="响应日期"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止日期"
                    ),
                ),
                (
                    "completion_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成日期"
                    ),
                ),
                (
                    "decline_reason",
                    models.TextField(blank=True, verbose_name="拒绝原因"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_assignments",
                        to="manuscripts.manuscript",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "审稿任务",
                "verbose_name_plural": "审稿任务",
                "unique_together": {("manuscript", "reviewer")},
            },
        ),
        migrations.CreateModel(
            name="ReviewForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "originality_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="原创性评分",
                    ),
                ),
                (
                    "technical_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="技术水平评分",
                    ),
                ),
                (
                    "presentation_score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="表达清晰度评分",
                    ),
                ),
                (
                    "comments_to_author",
                    models.TextField(blank=True, verbose_name="给作者的评语"),
                ),
                (
                    "comments_to_editor",
                    models.TextField(blank=True, verbose_name="给编辑的评语"),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACCEPT", "接受"),
                            ("MINOR_REVISION", "小修后接受"),
                            ("REJECT", "拒绝"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="建议决定",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_form",
                        to="review_process.reviewassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "评审表",
                "verbose_name_plural": "评审表",
            },
        ),
        migrations.CreateModel(
            name="ReviewerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expertise", models.TextField(blank=True, verbose_name="专业领域")),
                (
                    "max_reviews_per_month",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="每月最大审稿量",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "research_fields",
                    models.ManyToManyField(
                        to="accounts.researchfield", verbose_name="研究领域"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "审稿人资料",
                "verbose_name_plural": "审稿人资料",
            },
        ),
    ]
