# Generated by Django 4.2.15 on 2025-04-30 15:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManuscriptType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="类型名称"
                    ),
                ),
                (
                    "verbose_name",
                    models.CharField(max_length=100, verbose_name="显示名称"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
            ],
            options={
                "verbose_name": "稿件类型",
                "verbose_name_plural": "稿件类型",
            },
        ),
        migrations.CreateModel(
            name="Manuscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manuscript_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="稿件编号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "草稿"),
                            ("SUBMITTED", "已提交"),
                            ("UNDER_REVIEW", "外审中"),
                            ("REVISION_REQUIRED", "需要修改"),
                            ("REVISED", "已修改"),
                            ("ACCEPTED", "已接受"),
                            ("REJECTED", "已拒绝"),
                            ("REJECT_INITIAL", "初审拒绝"),
                            ("PUBLISHED", "已发表"),
                        ],
                        default="DRAFT",
                        max_length=30,
                        verbose_name="状态",
                    ),
                ),
                ("title_cn", models.CharField(max_length=200, verbose_name="中文标题")),
                ("title_en", models.CharField(max_length=200, verbose_name="英文标题")),
                ("authors", models.TextField(verbose_name="作者列表")),
                ("affiliations", models.TextField(verbose_name="作者单位")),
                (
                    "corresponding_author",
                    models.CharField(max_length=100, verbose_name="通讯作者"),
                ),
                ("abstract_cn", models.TextField(verbose_name="中文摘要")),
                ("abstract_en", models.TextField(verbose_name="英文摘要")),
                (
                    "keywords_cn",
                    models.CharField(max_length=200, verbose_name="中文关键词"),
                ),
                (
                    "keywords_en",
                    models.CharField(max_length=200, verbose_name="英文关键词"),
                ),
                (
                    "category_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="中图分类号"
                    ),
                ),
                (
                    "similarity_rate",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="查重率",
                    ),
                ),
                (
                    "manuscript_file",
                    models.FileField(upload_to="manuscripts/", verbose_name="原稿文件"),
                ),
                (
                    "revised_file",
                    models.FileField(
                        blank=True,
                        upload_to="manuscripts/revised/",
                        verbose_name="修改稿文件",
                    ),
                ),
                (
                    "additional_file",
                    models.FileField(
                        blank=True,
                        upload_to="manuscripts/additional/",
                        verbose_name="附加文件",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "submit_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "decision_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="决定时间"
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(blank=True, null=True, verbose_name="出版日期"),
                ),
                (
                    "volume",
                    models.IntegerField(blank=True, null=True, verbose_name="卷号"),
                ),
                (
                    "issue",
                    models.IntegerField(blank=True, null=True, verbose_name="期号"),
                ),
                (
                    "handling_editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handling_manuscripts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="责任编辑",
                    ),
                ),
                (
                    "research_field",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.researchfield",
                        verbose_name="研究领域",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_manuscripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="manuscripts.manuscripttype",
                        verbose_name="稿件类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "稿件",
                "verbose_name_plural": "稿件",
            },
        ),
        migrations.CreateModel(
            name="ManuscriptRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(verbose_name="版本号")),
                (
                    "revised_file",
                    models.FileField(
                        upload_to="manuscripts/revised/", verbose_name="修改稿文件"
                    ),
                ),
                ("comments", models.TextField(blank=True, verbose_name="修改说明")),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="manuscripts.manuscript",
                    ),
                ),
            ],
            options={
                "verbose_name": "稿件修改版本",
                "verbose_name_plural": "稿件修改版本",
                "unique_together": {("manuscript", "version")},
            },
        ),
    ]
