# Generated by Django 4.2.15 on 2025-04-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("manuscripts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_number", models.IntegerField(verbose_name="期号")),
                (
                    "publication_date",
                    models.DateField(blank=True, null=True, verbose_name="出版日期"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="是否发布"),
                ),
            ],
            options={
                "verbose_name": "期",
                "verbose_name_plural": "期",
            },
        ),
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "volume_number",
                    models.IntegerField(unique=True, verbose_name="卷号"),
                ),
                ("year", models.IntegerField(verbose_name="年份")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="是否发布"),
                ),
                (
                    "publish_date",
                    models.DateField(blank=True, null=True, verbose_name="发布日期"),
                ),
            ],
            options={
                "verbose_name": "卷",
                "verbose_name_plural": "卷",
            },
        ),
        migrations.CreateModel(
            name="ManuscriptPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_start",
                    models.IntegerField(blank=True, null=True, verbose_name="起始页码"),
                ),
                (
                    "page_end",
                    models.IntegerField(blank=True, null=True, verbose_name="结束页码"),
                ),
                (
                    "doi",
                    models.CharField(blank=True, max_length=100, verbose_name="DOI"),
                ),
                (
                    "publication_date",
                    models.DateField(blank=True, null=True, verbose_name="出版日期"),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manuscripts",
                        to="publication.issue",
                        verbose_name="期",
                    ),
                ),
                (
                    "manuscript",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manuscripts.manuscript",
                        verbose_name="稿件",
                    ),
                ),
            ],
            options={
                "verbose_name": "稿件出版",
                "verbose_name_plural": "稿件出版",
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="volume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="publication.volume",
                verbose_name="卷",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="issue",
            unique_together={("volume", "issue_number")},
        ),
    ]
