# Generated by Django 4.2.15 on 2025-04-30 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("SUBMISSION", "投稿通知"),
                            ("REVIEW_INVITE", "审稿邀请"),
                            ("REVIEW_REMINDER", "审稿提醒"),
                            ("DECISION", "编辑决定"),
                            ("REVISION", "修改要求"),
                            ("ACCEPT", "录用通知"),
                            ("REJECT", "退稿通知"),
                            ("PUBLICATION", "出版通知"),
                        ],
                        max_length=20,
                        verbose_name="通知类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("message", models.TextField(verbose_name="内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已读"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="相关链接"
                    ),
                ),
                (
                    "related_id",
                    models.CharField(blank=True, max_length=50, verbose_name="关联ID"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "ordering": ["-created_at"],
            },
        ),
    ]
